# @package _global_

defaults:
  - extras: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - callbacks: test.yaml
  - loggers: default.yaml
  - model: ppo.yaml
  - trainer: auto.yaml
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  # - override hydra/launcher: ray
  - _self_

model:
  frames_per_batch: 2
  total_frames: 10
  depth: 1
  n_mlp_layers: 1
  num_mlp_cells: 32
  num_cells: 32
trainer:
  max_steps: 3
  max_epochs: 1
  val_check_interval: 1
  log_every_n_steps: 1

hydra:
  mode: MULTIRUN
  sweeper:
    direction: minimize
    n_trials: 1
    n_jobs: 1
    params:
      model.n_mlp_layers: interval(2, 16)
      # model.depth: interval(2, 16)
      model.num_mlp_cells: interval(64, 1024)
      # model.num_cells: interval(64, 1024)
      model.clip_epsilon: interval(0.01, 0.4)
      model.entropy_eps: interval(0.00001, 0.001)
      model.gamma: interval(0.8, 0.999)
      model.lmbda: interval(0.8, 0.999)
optimize_metric: loss/train

ckpt_path: null

stage: fit
tag: PPO

