# @package _global_

defaults:
  - extras: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - callbacks: default.yaml
  - loggers: default.yaml
  - model: ppo.yaml
  - trainer: auto.yaml
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  # - override hydra/launcher: ray
  - _self_

model:
  frames_per_batch: 2
  total_frames: 10
trainer:
  max_steps: 3
  val_check_interval: 1
  log_every_n_steps: 1

hydra:
  mode: MULTIRUN
  sweeper:
    direction: minimize
    n_trials: 1
    n_jobs: 1
    params:
      model.n_mlp_layers: interval(2, 16)
optimize_metric: loss/train

ckpt_path: null

stage: fit
tag: PPO

